import Providers from '@/components/Providers'
import '../globals.css'
import { Inter } from 'next/font/google'
import DLayout from './components/DLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashborad Page',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
      <Providers>
        <DLayout>{children}</DLayout>
      </Providers>
    </body>
  </html>
  )
}
