import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashborad Page',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <div>
        <h1>Dashboard Header</h1>
        <hr />
        {children}
        <hr />
        <h1>Dashborad Footer</h1>
        </div>
  )
}
